#!/usr/bin/env python3
"""
gen_openram_configs.py – Generate OpenRAM Python config files for kv32 I-cache SRAMs.

Computes SRAM dimensions from the I-cache parameters and writes two config files:
  openram_tag_sram.py  – tag  SRAM (NUM_SETS × TAG_BITS)
  openram_data_sram.py – data SRAM (NUM_SETS × WPL × 32 bits)

Usage (called by 'make gen-mem'):
  python3 common/gen_openram_configs.py \
      --icache-size 4096 --icache-line-size 32 --icache-ways 2 \
      --pdk freepdk45 --output-dir lib/openram
"""

import argparse
import math
import os


def log2(n):
    v = int(round(math.log2(n)))
    assert (1 << v) == n, f"{n} is not a power of 2"
    return v


def main():
    p = argparse.ArgumentParser(description="Generate OpenRAM configs for kv32 cache SRAMs")
    p.add_argument("--icache-size",      type=int, default=4096, help="I-cache total bytes")
    p.add_argument("--icache-line-size", type=int, default=32,   help="Cache line size in bytes")
    p.add_argument("--icache-ways",      type=int, default=2,    help="Cache associativity")
    p.add_argument("--pdk",              default="freepdk45",    help="PDK: freepdk45 | asap7")
    p.add_argument("--output-dir",       default="lib/openram",  help="Output directory")
    args = p.parse_args()

    # Derived dimensions (must match kv32_icache.sv localparams)
    num_sets       = args.icache_size // (args.icache_line_size * args.icache_ways)
    words_per_line = args.icache_line_size // 4
    byte_off_bits  = log2(args.icache_line_size)
    index_bits     = log2(num_sets)
    tag_bits       = 32 - byte_off_bits - index_bits
    data_depth     = num_sets * words_per_line

    # PDK-specific OpenRAM settings
    if args.pdk == "freepdk45":
        tech_name       = "freepdk45"
        supply_voltages = [1.1]
    elif args.pdk == "asap7":
        tech_name       = "asap7"
        supply_voltages = [0.7]
    else:
        tech_name       = args.pdk
        supply_voltages = [1.8]

    tag_name  = f"sram_1rw_{num_sets}x{tag_bits}"
    data_name = f"sram_1rw_{data_depth}x32"

    header = (
        "# Auto-generated by gen_openram_configs.py – do not edit manually.\n"
        f"# Cache params: ICACHE_SIZE={args.icache_size}B  "
        f"LINE={args.icache_line_size}B  WAYS={args.icache_ways}\n"
        "import os\n"
        "OPENRAM_HOME      = os.environ.get('OPENRAM_HOME', '/opt/OpenRAM')\n"
        "OPENRAM_TECH_PATH = os.path.join(OPENRAM_HOME, 'technology')\n"
    )

    common = (
        f"num_rw_ports    = 1\n"
        f"num_r_ports     = 0\n"
        f"num_w_ports     = 0\n"
        f"tech_name       = \"{tech_name}\"\n"
        f"process_corners = [\"TT\"]\n"
        f"supply_voltages = {supply_voltages}\n"
        f"temperatures    = [25]\n"
        f"route_supplies  = True\n"
        f"check_lvsdrc    = False\n"
        f"output_path     = \".\"\n"
    )

    tag_cfg = (
        header
        + f"# I-cache tag SRAM: {num_sets} words × {tag_bits} bits\n"
        + f"word_size       = {tag_bits}\n"
        + f"num_words       = {num_sets}\n"
        + common
        + f"output_name     = \"{tag_name}\"\n"
    )

    data_cfg = (
        header
        + f"# I-cache data SRAM: {data_depth} words × 32 bits\n"
        + f"word_size       = 32\n"
        + f"num_words       = {data_depth}\n"
        + common
        + f"output_name     = \"{data_name}\"\n"
    )

    os.makedirs(args.output_dir, exist_ok=True)
    with open(os.path.join(args.output_dir, "openram_tag_sram.py"), "w") as f:
        f.write(tag_cfg)
    with open(os.path.join(args.output_dir, "openram_data_sram.py"), "w") as f:
        f.write(data_cfg)

    print(f"Tag  SRAM: {num_sets} × {tag_bits} bits  →  {tag_name}")
    print(f"Data SRAM: {data_depth} × 32 bits      →  {data_name}")
    print(f"Configs written to {args.output_dir}/")


if __name__ == "__main__":
    main()
