#!/usr/bin/env python3
"""
gen_openram_configs.py – Generate OpenRAM Python config files for kv32 I-cache and D-cache SRAMs.

Computes SRAM dimensions from the cache parameters and writes four config files:
  openram_tag_sram.py        – I-cache tag  SRAM (NUM_SETS × TAG_BITS)
  openram_data_sram.py       – I-cache data SRAM (NUM_SETS × WPL × 32 bits)
  openram_dcache_tag_sram.py – D-cache tag  SRAM (NUM_SETS × TAG_BITS)
  openram_dcache_data_sram.py – D-cache data SRAM (NUM_SETS × WPL × 32 bits)

Usage (called by 'make gen-mem'):
  python3 common/gen_openram_configs.py \
      --icache-size 4096 --icache-line-size 32 --icache-ways 2 \
      --dcache-size 4096 --dcache-line-size 32 --dcache-ways 2 \
      --pdk freepdk45 --output-dir lib/openram
"""

import argparse
import math
import os

def log2(n):
    v = int(round(math.log2(n)))
    assert (1 << v) == n, f"{n} is not a power of 2"
    return v

def main():
    p = argparse.ArgumentParser(description="Generate OpenRAM configs for kv32 cache SRAMs")
    p.add_argument("--icache-size",      type=int, default=4096, help="I-cache total bytes")
    p.add_argument("--icache-line-size", type=int, default=32,   help="I-cache line size in bytes")
    p.add_argument("--icache-ways",      type=int, default=2,    help="I-cache associativity")
    p.add_argument("--dcache-size",      type=int, default=4096, help="D-cache total bytes")
    p.add_argument("--dcache-line-size", type=int, default=32,   help="D-cache line size in bytes")
    p.add_argument("--dcache-ways",      type=int, default=2,    help="D-cache associativity")
    p.add_argument("--pdk",              default="freepdk45",    help="PDK: freepdk45 | asap7")
    p.add_argument("--output-dir",       default="lib/openram",  help="Output directory")
    args = p.parse_args()

    # I-cache derived dimensions (must match kv32_icache.sv localparams)
    inum_sets       = args.icache_size // (args.icache_line_size * args.icache_ways)
    iwords_per_line = args.icache_line_size // 4
    ibyte_off_bits  = log2(args.icache_line_size)
    iindex_bits     = log2(inum_sets)
    itag_bits       = 32 - ibyte_off_bits - iindex_bits
    idata_depth     = inum_sets * iwords_per_line

    # D-cache derived dimensions (must match kv32_dcache.sv localparams)
    dnum_sets       = args.dcache_size // (args.dcache_line_size * args.dcache_ways)
    dwords_per_line = args.dcache_line_size // 4
    dbyte_off_bits  = log2(args.dcache_line_size)
    dindex_bits     = log2(dnum_sets)
    dtag_bits       = 32 - dbyte_off_bits - dindex_bits
    ddata_depth     = dnum_sets * dwords_per_line

    # PDK-specific OpenRAM settings
    if args.pdk == "freepdk45":
        tech_name       = "freepdk45"
        supply_voltages = [1.1]
    elif args.pdk == "asap7":
        tech_name       = "asap7"
        supply_voltages = [0.7]
    else:
        tech_name       = args.pdk
        supply_voltages = [1.8]

    itag_name  = f"sram_1rw_{inum_sets}x{itag_bits}"
    idata_name = f"sram_1rw_{idata_depth}x32"
    dtag_name  = f"sram_1rw_{dnum_sets}x{dtag_bits}"
    ddata_name = f"sram_1rw_{ddata_depth}x32"

    header = (
        "# Auto-generated by gen_openram_configs.py – do not edit manually.\n"
        f"# Cache params: ICACHE_SIZE={args.icache_size}B  "
        f"LINE={args.icache_line_size}B  WAYS={args.icache_ways}\n"
        "import os\n"
        "OPENRAM_HOME      = os.environ.get('OPENRAM_HOME', '/opt/OpenRAM')\n"
        "OPENRAM_TECH_PATH = os.path.join(OPENRAM_HOME, 'technology')\n"
    )

    dcache_header = (
        "# Auto-generated by gen_openram_configs.py – do not edit manually.\n"
        f"# Cache params: DCACHE_SIZE={args.dcache_size}B  "
        f"LINE={args.dcache_line_size}B  WAYS={args.dcache_ways}\n"
        "import os\n"
        "OPENRAM_HOME      = os.environ.get('OPENRAM_HOME', '/opt/OpenRAM')\n"
        "OPENRAM_TECH_PATH = os.path.join(OPENRAM_HOME, 'technology')\n"
    )

    common = (
        f"num_rw_ports    = 1\n"
        f"num_r_ports     = 0\n"
        f"num_w_ports     = 0\n"
        f"tech_name       = \"{tech_name}\"\n"
        f"process_corners = [\"TT\"]\n"
        f"supply_voltages = {supply_voltages}\n"
        f"temperatures    = [25]\n"
        f"route_supplies  = True\n"
        f"check_lvsdrc    = False\n"
        f"output_path     = \".\"\n"
    )

    tag_cfg = (
        header
        + f"# I-cache tag SRAM: {inum_sets} words \u00d7 {itag_bits} bits\n"
        + f"word_size       = {itag_bits}\n"
        + f"num_words       = {inum_sets}\n"
        + common
        + f"output_name     = \"{itag_name}\"\n"
    )

    data_cfg = (
        header
        + f"# I-cache data SRAM: {idata_depth} words \u00d7 32 bits\n"
        + f"word_size       = 32\n"
        + f"num_words       = {idata_depth}\n"
        + common
        + f"output_name     = \"{idata_name}\"\n"
    )

    dcache_tag_cfg = (
        dcache_header
        + f"# D-cache tag SRAM: {dnum_sets} words \u00d7 {dtag_bits} bits\n"
        + f"word_size       = {dtag_bits}\n"
        + f"num_words       = {dnum_sets}\n"
        + common
        + f"output_name     = \"{dtag_name}\"\n"
    )

    dcache_data_cfg = (
        dcache_header
        + f"# D-cache data SRAM: {ddata_depth} words \u00d7 32 bits\n"
        + f"word_size       = 32\n"
        + f"num_words       = {ddata_depth}\n"
        + common
        + f"output_name     = \"{ddata_name}\"\n"
    )

    os.makedirs(args.output_dir, exist_ok=True)
    with open(os.path.join(args.output_dir, "openram_tag_sram.py"), "w") as f:
        f.write(tag_cfg)
    with open(os.path.join(args.output_dir, "openram_data_sram.py"), "w") as f:
        f.write(data_cfg)
    with open(os.path.join(args.output_dir, "openram_dcache_tag_sram.py"), "w") as f:
        f.write(dcache_tag_cfg)
    with open(os.path.join(args.output_dir, "openram_dcache_data_sram.py"), "w") as f:
        f.write(dcache_data_cfg)

    print(f"I-cache tag  SRAM: {inum_sets} \u00d7 {itag_bits} bits  \u2192  {itag_name}")
    print(f"I-cache data SRAM: {idata_depth} \u00d7 32 bits       \u2192  {idata_name}")
    print(f"D-cache tag  SRAM: {dnum_sets} \u00d7 {dtag_bits} bits  \u2192  {dtag_name}")
    print(f"D-cache data SRAM: {ddata_depth} \u00d7 32 bits       \u2192  {ddata_name}")
    print(f"Configs written to {args.output_dir}/")

if __name__ == "__main__":
    main()
