../rtl/kv32/core/kv32_pkg.sv
../rtl/kv32/core/kv32_ib.sv
../rtl/kv32/core/kv32_regfile.sv
../rtl/kv32/core/kv32_csr.sv
../rtl/kv32/core/kv32_alu.sv
../rtl/kv32/core/kv32_bht.sv
../rtl/kv32/core/kv32_btb.sv
../rtl/kv32/core/kv32_decoder.sv
../rtl/kv32/core/kv32_rvc.sv
../rtl/kv32/core/kv32_sb.sv
../rtl/kv32/core/kv32_ras.sv
../rtl/kv32/core/kv32_core.sv
../syn/lib/sram_1rw.sv
../rtl/axi/axi_pkg.sv
../rtl/axi/axi_arbiter.sv
../rtl/axi/axi_dma.sv
../rtl/axi/axi_xbar.sv
../rtl/axi/axi_clint.sv
../rtl/axi/axi_i2c.sv
../rtl/axi/axi_spi.sv
../rtl/axi/axi_plic.sv
../rtl/axi/axi_uart.sv
../rtl/axi/axi_gpio.sv
../rtl/axi/axi_timer.sv
../rtl/axi/axi_wdt.sv
../rtl/axi/axi_magic.sv
../rtl/axi/axi_top.sv
../rtl/kv32/mem_axi.sv
../rtl/kv32/mem_axi_ro.sv
../rtl/kv32/kv32_icache.sv
../rtl/kv32/kv32_dcache.sv
../rtl/kv32/kv32_pm.sv
../rtl/kv32/jtag/kv32_dtm.sv
../rtl/kv32/kv32_top.sv
../rtl/kv32/jtag/jtag_tap.sv
../rtl/kv32/jtag/cjtag_bridge.sv
../rtl/kv32/jtag/jtag_top.sv
../rtl/kv32_soc.sv
