../rtl/core/kv32_pkg.sv
../rtl/core/kv32_ib.sv
../rtl/core/kv32_regfile.sv
../rtl/core/kv32_csr.sv
../rtl/core/kv32_alu.sv
../rtl/core/kv32_decoder.sv
../rtl/core/kv32_rvc.sv
../rtl/core/kv32_sb.sv
../rtl/core/kv32_core.sv
../syn/lib/sram_1rw.sv
../rtl/axi_pkg.sv
../rtl/axi_arbiter.sv
../rtl/axi_dma.sv
../rtl/axi_xbar.sv
../rtl/axi_clint.sv
../rtl/axi_i2c.sv
../rtl/axi_spi.sv
../rtl/axi_plic.sv
../rtl/axi_uart.sv
../rtl/axi_gpio.sv
../rtl/axi_timer.sv
../rtl/axi_magic.sv
../rtl/mem_axi.sv
../rtl/mem_axi_ro.sv
../rtl/kv32_icache.sv
../rtl/kv32_pm.sv
../rtl/kv32_dtm.sv
../rtl/jtag/jtag_tap.sv
../rtl/jtag/cjtag_bridge.sv
../rtl/jtag/jtag_top.sv
../rtl/kv32_soc.sv
